### ISSUE TITLE
Please inject a LICENSE -file to the repo

### ISSUE THREAD

**Issue by JanneKiiskila** [pijyoi/jsonrpc#6]
Hi,

you are graciously indicating a MIT license, but it's there in a rather obscure way https://github.com/pijyoi/jsonrpc/blob/master/README.md
"Since significant functionality is provided by jansson library, the same licence is chosen to be used by this code."

I would recommend putting an explicit LICENSE -file in the root of this repository to make it more explicit.

Thank you!

**Comment by pijyoi** [comment]
closed by af216ce710c011aee0e0eb2d1093330742e441b1

**Comment by JanneKiiskila** [comment]
Excellent, thank you for a very quick response!
